# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'viewer_ui_design.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QLabel, QPushButton,
    QSizePolicy, QWidget)

class Ui_MedAnalyzer(object):
    def setupUi(self, MedAnalyzer):
        if not MedAnalyzer.objectName():
            MedAnalyzer.setObjectName(u"MedAnalyzer")
        MedAnalyzer.resize(1280, 720)
        icon = QIcon()
        icon.addFile(u"assets/favicon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MedAnalyzer.setWindowIcon(icon)
        self.image_label = QLabel(MedAnalyzer)
        self.image_label.setObjectName(u"image_label")
        self.image_label.setGeometry(QRect(130, 70, 1024, 600))
        self.image_label.setStyleSheet(u"background-color: black;\n"
"")
        self.image_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.image_label.setMargin(2)
        self.rotate_right = QPushButton(MedAnalyzer)
        self.rotate_right.setObjectName(u"rotate_right")
        self.rotate_right.setGeometry(QRect(1190, 450, 51, 51))
        font = QFont()
        font.setBold(False)
        font.setKerning(True)
        self.rotate_right.setFont(font)
        self.rotate_right.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.rotate_right.setStyleSheet(u"padding: 0px")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ViewRefresh))
        self.rotate_right.setIcon(icon1)
        self.rotate_right.setIconSize(QSize(32, 32))
        self.rotate_left = QPushButton(MedAnalyzer)
        self.rotate_left.setObjectName(u"rotate_left")
        self.rotate_left.setGeometry(QRect(1190, 390, 51, 51))
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ViewRestore))
        self.rotate_left.setIcon(icon2)
        self.rotate_left.setIconSize(QSize(32, 32))
        self.rotation_reset = QPushButton(MedAnalyzer)
        self.rotation_reset.setObjectName(u"rotation_reset")
        self.rotation_reset.setGeometry(QRect(1190, 510, 51, 51))
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentRevert))
        self.rotation_reset.setIcon(icon3)
        self.rotation_reset.setIconSize(QSize(32, 32))
        self.zoom_reset = QPushButton(MedAnalyzer)
        self.zoom_reset.setObjectName(u"zoom_reset")
        self.zoom_reset.setGeometry(QRect(1190, 210, 51, 51))
        self.zoom_reset.setIcon(icon3)
        self.zoom_reset.setIconSize(QSize(32, 32))
        self.zoom_in = QPushButton(MedAnalyzer)
        self.zoom_in.setObjectName(u"zoom_in")
        self.zoom_in.setGeometry(QRect(1190, 90, 51, 51))
        self.zoom_in.setFont(font)
        self.zoom_in.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.zoom_in.setStyleSheet(u"padding: 0px")
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomIn))
        self.zoom_in.setIcon(icon4)
        self.zoom_in.setIconSize(QSize(32, 32))
        self.zoom_out = QPushButton(MedAnalyzer)
        self.zoom_out.setObjectName(u"zoom_out")
        self.zoom_out.setGeometry(QRect(1190, 150, 51, 51))
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomOut))
        self.zoom_out.setIcon(icon5)
        self.zoom_out.setIconSize(QSize(32, 32))
        self.close_image = QPushButton(MedAnalyzer)
        self.close_image.setObjectName(u"close_image")
        self.close_image.setGeometry(QRect(40, 210, 51, 51))
        icon6 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditClear))
        self.close_image.setIcon(icon6)
        self.close_image.setIconSize(QSize(32, 32))
        self.save_image_as = QPushButton(MedAnalyzer)
        self.save_image_as.setObjectName(u"save_image_as")
        self.save_image_as.setGeometry(QRect(40, 150, 51, 51))
        icon7 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSaveAs))
        self.save_image_as.setIcon(icon7)
        self.save_image_as.setIconSize(QSize(32, 32))
        self.open_image = QPushButton(MedAnalyzer)
        self.open_image.setObjectName(u"open_image")
        self.open_image.setGeometry(QRect(40, 90, 51, 51))
        self.open_image.setFont(font)
        self.open_image.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.open_image.setStyleSheet(u"padding: 0px")
        icon8 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.open_image.setIcon(icon8)
        self.open_image.setIconSize(QSize(32, 32))
        self.send_image_to = QPushButton(MedAnalyzer)
        self.send_image_to.setObjectName(u"send_image_to")
        self.send_image_to.setGeometry(QRect(1190, 590, 51, 51))
        icon9 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSend))
        self.send_image_to.setIcon(icon9)
        self.send_image_to.setIconSize(QSize(32, 32))
        self.viewer_title = QLabel(MedAnalyzer)
        self.viewer_title.setObjectName(u"viewer_title")
        self.viewer_title.setGeometry(QRect(-130, 10, 471, 31))
        font1 = QFont()
        font1.setFamilies([u"Lucida Fax"])
        font1.setPointSize(18)
        font1.setBold(True)
        self.viewer_title.setFont(font1)
        self.viewer_title.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.viewer_title.setStyleSheet(u"")
        self.viewer_title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.viewer_title_2 = QLabel(MedAnalyzer)
        self.viewer_title_2.setObjectName(u"viewer_title_2")
        self.viewer_title_2.setGeometry(QRect(-110, 31, 451, 31))
        font2 = QFont()
        font2.setFamilies([u"Lucida Fax"])
        font2.setPointSize(8)
        font2.setBold(True)
        self.viewer_title_2.setFont(font2)
        self.viewer_title_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.viewer_title_2.setStyleSheet(u"")
        self.viewer_title_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.viewer_title_3 = QLabel(MedAnalyzer)
        self.viewer_title_3.setObjectName(u"viewer_title_3")
        self.viewer_title_3.setGeometry(QRect(560, 680, 160, 31))
        font3 = QFont()
        font3.setFamilies([u"Lucida Fax"])
        font3.setPointSize(8)
        font3.setBold(False)
        self.viewer_title_3.setFont(font3)
        self.viewer_title_3.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.viewer_title_3.setStyleSheet(u"")
        self.viewer_title_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.viewer_title_4 = QLabel(MedAnalyzer)
        self.viewer_title_4.setObjectName(u"viewer_title_4")
        self.viewer_title_4.setGeometry(QRect(200, 11, 41, 41))
        font4 = QFont()
        font4.setFamilies([u"Lucida Fax"])
        font4.setPointSize(20)
        font4.setBold(True)
        self.viewer_title_4.setFont(font4)
        self.viewer_title_4.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.viewer_title_4.setStyleSheet(u"")
        self.viewer_title_4.setPixmap(QPixmap(u"assets/favicon.png"))
        self.viewer_title_4.setScaledContents(True)
        self.viewer_title_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.user_info_label = QLabel(MedAnalyzer)
        self.user_info_label.setObjectName(u"user_info_label")
        self.user_info_label.setGeometry(QRect(1070, 20, 191, 41))
        font5 = QFont()
        font5.setFamilies([u"Lucida Fax"])
        font5.setBold(True)
        self.user_info_label.setFont(font5)
        self.user_info_label.setStyleSheet(u"font-size: 12px; font-weight: bold;")
        self.user_info_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTop|Qt.AlignmentFlag.AlignTrailing)
        self.mouse_position_label = QLabel(MedAnalyzer)
        self.mouse_position_label.setObjectName(u"mouse_position_label")
        self.mouse_position_label.setGeometry(QRect(140, 630, 171, 31))
        font6 = QFont()
        font6.setFamilies([u"Consolas"])
        font6.setBold(False)
        self.mouse_position_label.setFont(font6)
        self.mouse_position_label.setStyleSheet(u"font-size: 20px; font-weight: light;\n"
"background-color: rgba(128,128,128, 35);\n"
"border-radius: 5px;")
        self.mouse_position_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.mouse_position_label.setMargin(8)
        self.dicom_info_label = QLabel(MedAnalyzer)
        self.dicom_info_label.setObjectName(u"dicom_info_label")
        self.dicom_info_label.setGeometry(QRect(760, 570, 381, 91))
        font7 = QFont()
        font7.setFamilies([u"Consolas"])
        font7.setBold(True)
        self.dicom_info_label.setFont(font7)
        self.dicom_info_label.setStyleSheet(u"font-size: 16px; font-weight: light;\n"
"background-color: rgba(128,128,128, 35);\n"
"border-radius: 5px;")
        self.dicom_info_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.dicom_info_label.setMargin(8)
        self.rotate_right.raise_()
        self.rotate_left.raise_()
        self.rotation_reset.raise_()
        self.zoom_reset.raise_()
        self.zoom_in.raise_()
        self.zoom_out.raise_()
        self.close_image.raise_()
        self.save_image_as.raise_()
        self.open_image.raise_()
        self.send_image_to.raise_()
        self.viewer_title.raise_()
        self.viewer_title_2.raise_()
        self.viewer_title_3.raise_()
        self.viewer_title_4.raise_()
        self.user_info_label.raise_()
        self.image_label.raise_()
        self.dicom_info_label.raise_()
        self.mouse_position_label.raise_()

        self.retranslateUi(MedAnalyzer)

        QMetaObject.connectSlotsByName(MedAnalyzer)
    # setupUi

    def retranslateUi(self, MedAnalyzer):
        MedAnalyzer.setWindowTitle(QCoreApplication.translate("MedAnalyzer", u"MedAnalyzer", None))
        self.image_label.setText("")
        self.rotate_right.setText("")
        self.rotate_left.setText("")
        self.rotation_reset.setText("")
        self.zoom_reset.setText("")
        self.zoom_in.setText("")
        self.zoom_out.setText("")
        self.close_image.setText("")
        self.save_image_as.setText("")
        self.open_image.setText("")
        self.send_image_to.setText("")
        self.viewer_title.setText(QCoreApplication.translate("MedAnalyzer", u"MedAnalyzer", None))
        self.viewer_title_2.setText(QCoreApplication.translate("MedAnalyzer", u"Visor de Im\u00e1genes M\u00e9dicas", None))
        self.viewer_title_3.setText(QCoreApplication.translate("MedAnalyzer", u"Versi\u00f3n preliminar", None))
        self.viewer_title_4.setText("")
        self.user_info_label.setText("")
        self.mouse_position_label.setText("")
        self.dicom_info_label.setText("")
    # retranslateUi

